<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['network_visualiser_app_description'] = 'Приложение "Сеть визуально" захватывает и показывает поток данных, проходящих по сети в реальном времени, показывает источник, место назначения и информацию протокола, а также дополнительно полосу пропускания и количество данных за указанный интервал.';
$lang['network_visualiser_app_name'] = 'Сеть визуально';
$lang['network_visualiser_display'] = 'Показать';
$lang['network_visualiser_display_invalid'] = 'Невозможно показать.';
$lang['network_visualiser_interval'] = 'Интервал обновления (секунды)';
$lang['network_visualiser_interval_is_invalid'] = 'Интервал является недействительным.';
$lang['network_visualiser_report'] = 'Формат отчета';
$lang['network_visualiser_report_detailed'] = 'Табличный - Детальный';
$lang['network_visualiser_report_graphical'] = 'Графический';
$lang['network_visualiser_report_invalid'] = 'Тип отчета является недействительным.';
$lang['network_visualiser_report_simple'] = 'Табличный - Простой';
$lang['network_visualiser_top_users'] = 'Главные потребители пропускной способности';
$lang['network_visualiser_total_transfer'] = 'Всего передано';
$lang['network_visualiser_traffic_summary'] = 'Сводка сетевого трафика';
