<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['network_visualiser_app_description'] = 'The Network Visualizer app captures and displays data flow traversing your network in real-time, displaying source, destination and protocol information in addition to either bandwidth usage or total data captured over an interval.';
$lang['network_visualiser_app_name'] = 'Network Visualizer';
$lang['network_visualiser_display'] = 'Anzeigen';
$lang['network_visualiser_display_invalid'] = 'Ausgabe ist ungültig.';
$lang['network_visualiser_interval'] = 'Updateintervall (Sekunden)';
$lang['network_visualiser_interval_is_invalid'] = 'Intervall ist ungültig.';
$lang['network_visualiser_report'] = 'Berichtsformat';
$lang['network_visualiser_report_detailed'] = 'Tabellarisch - Detailliert';
$lang['network_visualiser_report_graphical'] = 'Grafisch';
$lang['network_visualiser_report_invalid'] = 'Berichtsart ist ungültig.';
$lang['network_visualiser_report_simple'] = 'Tabellarisch - Einfach';
$lang['network_visualiser_top_users'] = 'Top Bandbreitenkonsumenten';
$lang['network_visualiser_total_transfer'] = 'Verkehr Gesamt';
$lang['network_visualiser_traffic_summary'] = 'Zusammenfassung des Netzwerkverkehrs';
