<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['network_visualiser_app_description'] = 'O Aplicativo Visualizador de Rede captura e mostra o fluxo de dados que atravessa sua rede em tempo real, exibindo origem, destino e informações de protocolo, ou o uso de banda ou total de dados capturados durante um intervalo.';
$lang['network_visualiser_app_name'] = 'Visualizador de Rede';
$lang['network_visualiser_display'] = 'Exibir';
$lang['network_visualiser_display_invalid'] = 'Exibição inválida.';
$lang['network_visualiser_interval'] = 'Intervalo de Atualização (segundos)';
$lang['network_visualiser_interval_is_invalid'] = 'Intervalo inválido.';
$lang['network_visualiser_report'] = 'Formato de Relatório';
$lang['network_visualiser_report_detailed'] = 'Tabular - Detalhado';
$lang['network_visualiser_report_graphical'] = 'Gráfico';
$lang['network_visualiser_report_invalid'] = 'Tipo de Relatório Inválido.';
$lang['network_visualiser_report_simple'] = 'Tabular - Simples';
$lang['network_visualiser_top_users'] = 'Maiores Consumidores de Banda';
$lang['network_visualiser_total_transfer'] = 'Transferencia Total';
$lang['network_visualiser_traffic_summary'] = 'Resumo de Tráfego de Rede';
