<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['network_visualiser_app_description'] = 'The Network Visualizer app captures and displays data flow traversing your network in real-time, displaying source, destination and protocol information in addition to either bandwidth usage or total data captured over an interval.';
$lang['network_visualiser_app_name'] = 'Network Visualizer';
$lang['network_visualiser_display'] = 'Exibir';
$lang['network_visualiser_display_invalid'] = 'Exibição inválida.';
$lang['network_visualiser_interval'] = 'Intervalo de Atualização (segundos)';
$lang['network_visualiser_interval_is_invalid'] = 'Intervalo inválido.';
$lang['network_visualiser_report'] = 'Formato de Relatório';
$lang['network_visualiser_report_detailed'] = 'Tabular - Detalhado';
$lang['network_visualiser_report_graphical'] = 'Gráfico';
$lang['network_visualiser_report_invalid'] = 'Tipo de Relatório Inválido.';
$lang['network_visualiser_report_simple'] = 'Tabular - Simples';
$lang['network_visualiser_top_users'] = 'Maiores Consumidores de Banda';
$lang['network_visualiser_total_transfer'] = 'Transferencia Total';
$lang['network_visualiser_traffic_summary'] = 'Resumo de Tráfego de Rede';
