<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['network_visualiser_app_description'] = 'Nätverksvisualiserings-appen fångar in och visar dataflödet som flödar i ditt nätverk i realtid. Appen visar källa, destination och protokollinformation i förhållande till antingen bandbreddsanvändning eller totala mängden data över ett intervall.';
$lang['network_visualiser_app_name'] = 'Nätverksvisualiseraren';
$lang['network_visualiser_display'] = 'Visa';
$lang['network_visualiser_display_invalid'] = 'Går inte att visa.';
$lang['network_visualiser_interval'] = 'Uppdateringsintervall (sekunder)';
$lang['network_visualiser_interval_is_invalid'] = 'Intervallet är ogiltigt.';
$lang['network_visualiser_report'] = 'Rapportformat';
$lang['network_visualiser_report_detailed'] = 'Tabell - Detaljerad';
$lang['network_visualiser_report_graphical'] = 'Grafisk';
$lang['network_visualiser_report_invalid'] = 'Rapporttypen är ogiltig.';
$lang['network_visualiser_report_simple'] = 'Tabell - Enkel';
$lang['network_visualiser_top_users'] = 'Toppkonsumere av bandbredd';
$lang['network_visualiser_total_transfer'] = 'Total överföring';
$lang['network_visualiser_traffic_summary'] = 'Summering nätverkstrafik';
