#!/usr/clearos/sandbox/usr/bin/php
<?php

/**
 * Network Visualiser scan.
 *
 * @category   apps
 * @package    network_visualiser
 * @subpackage scripts
 * @author     ClearFoundation <developer@clearfoundation.com>
 * @copyright  2014 ClearFoundation
 * @license    http://www.gnu.org/copyleft/lgpl.html GNU Lesser General Public License version 3 or later
 * @link       http://www.clearfoundation.com/docs/developer/apps/network_visualiser/
 */

///////////////////////////////////////////////////////////////////////////////
// N A M E S P A C E
///////////////////////////////////////////////////////////////////////////////

namespace clearos\apps\network_visualiser;

///////////////////////////////////////////////////////////////////////////////
// B O O T S T R A P
///////////////////////////////////////////////////////////////////////////////

$bootstrap = getenv('CLEAROS_BOOTSTRAP') ? getenv('CLEAROS_BOOTSTRAP') : '/usr/clearos/framework/shared';
require_once $bootstrap . '/bootstrap.php';

///////////////////////////////////////////////////////////////////////////////
// T R A N S L A T I O N S
///////////////////////////////////////////////////////////////////////////////

clearos_load_language('network_visualiser');

///////////////////////////////////////////////////////////////////////////////
// D E P E N D E N C I E S
///////////////////////////////////////////////////////////////////////////////

// Classes
//--------

use \clearos\apps\network_visualiser\Network_Visualiser as Network_Visualiser;
use \clearos\apps\base\File as File;
use \clearos\apps\base\Shell as Shell;

clearos_load_library('network_visualiser/Network_Visualiser');
clearos_load_library('base/File');
clearos_load_library('base/Shell');

// Exceptions
//-----------

use \Exception as Exception;

///////////////////////////////////////////////////////////////////////////////
// M A I N
///////////////////////////////////////////////////////////////////////////////

//--------------------------------------------------------------------
// Command line options
//--------------------------------------------------------------------

$short_options  = '';

// Common
$short_options .= 'i::'; // Interface
$short_options .= 't::'; // Interval Time
$short_options .= 'x::'; // Filters
$short_options .= 'f::'; // Log file
$short_options .= 'r::'; // Reset
$short_options .= 'o::'; // Output
$short_options .= 'h';   // Help

$helpopts  = '
  Common Options
  --------------

  -i=interface (optional - default first online interface)
  -t=interval (optional - default 5 seconds)
  -x=filter  (optional - default no filter - supports multiple filters: -xsrcport=80 -xdestip=192.168.0.1)
  -f=log file (optional - log file, default is nv_logfile)
  -r=force reset (optional - reset log file output)
  -o=output (json [default] or stdout)
  -h: help

';

// Handle command line options
//----------------------------

$options = getopt($short_options);

$interface = isset($options['i']) ? $options['i'] : NULL;
$interval = isset($options['t']) ? $options['t'] : 5;
$filters = isset($options['x']) ? $options['x'] : NULL;
$log_file = isset($options['f']) ? $options['f'] : NULL;
$reset = isset($options['r']) ? $options['r'] : NULL;
$output = isset($options['o']) ? $options['o'] : 'stdout';
$help = isset($options['h']) ? TRUE : FALSE;

if ($help) {
    echo "usage: " . $argv[0] . " [options]\n";
    echo $helpopts;
    exit(0);
}

if (php_sapi_name() === 'cli') {
    $user = exec('whoami');
    if ($user != 'root') {
        update_status(-1, "Script must be run as 'root'.");
        exit(1);
    }
}

if ($filters != NULL && !is_array($filters))
    $filters = array($filters);

$network_visualiser = new Network_Visualiser();

try {
    if ($interface == NULL) {
        $interfaces = $network_visualiser->get_interface_options();
        $interface = key($interfaces);
    }

    if ($log_file == NULL)
        $log_file = Network_Visualiser::FILE_LOG . "_in_progress";
    else
        $log_file = $log_file . "_in_progress";

    $file = new File(CLEAROS_TEMP_DIR . "/" . $log_file);

    if ($file->exists() && $reset) {
        update_status(0, "Forcing reset of log file and starting new scan.");
        $file->delete();
    } elseif ($file->exists()) {
        update_status(0, "Scan in progress...[" . $file->get_filename() . "]");
        return;
    }

    $file->create('webconfig', 'webconfig', '0644');
    $file->add_lines("interval=$interval\n");
    $file->add_lines("stop=" . strtotime("+$interval seconds") . "\n");

    $shell = new Shell();
    $args = "-i $interface --display text -t $interval --format '$" . implode("$,$", $network_visualiser->get_fields()) . "$'";

    $options = array('env' => "LANG=en_US", 'log' => basename($file->get_filename()));

    $retval = $shell->execute(Network_Visualiser::CMD_JNETTOP, $args, TRUE, $options);

    if ($retval != 0) {
        $errstr = $shell->get_last_output_line();
        throw new Engine_Exception($errstr, CLEAROS_ERROR);
    }
    $file->move_to(CLEAROS_TEMP_DIR . "/" . preg_replace("/_in_progress/", "", $log_file));
    echo "Done FIXME\n";
} catch (Exception $e) {
    update_status(-1, clearos_exception_message($e));
}

/**
 * Update status.
 *
 * @param string $code     status code
 * @param string $msg      status message
 *
 * @return void
 */

function update_status($code, $msg)
{
    global $output;

    if ($output == 'stdout') {
        echo $msg . "\n";
    } else {
        $info = array (
            'code' => $code,
            'timestamp' => time(),
            'msg' => $msg
        );
        echo json_encode($info) . "\n"; 
    }
}
// vim: syntax=php ts=4
