<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['network_visualiser_app_description'] = 'The Network Visualizer app captures and displays data flow traversing your network in real-time, displaying source, destination and protocol information in addition to either bandwidth usage or total data captured over an interval.';
$lang['network_visualiser_app_name'] = 'Network Visualizer';
$lang['network_visualiser_display'] = 'Wyświetl';
$lang['network_visualiser_display_invalid'] = 'Wyświetlenie jest nieprawidłowe.';
$lang['network_visualiser_interval'] = 'Okres odświeżania (w sekundach)';
$lang['network_visualiser_interval_is_invalid'] = 'Przedział czasu jest nieprawidłowy.';
$lang['network_visualiser_report'] = 'Format raportu';
$lang['network_visualiser_report_detailed'] = 'Tabelaryczny - szczegółowy';
$lang['network_visualiser_report_graphical'] = 'Graficzny';
$lang['network_visualiser_report_invalid'] = 'Typ raportu jest nieprawidłowy.';
$lang['network_visualiser_report_simple'] = 'Tabelaryczny - ogólny';
$lang['network_visualiser_top_users'] = 'Najbardziej obciążający pasmo';
$lang['network_visualiser_total_transfer'] = 'Całkowity transfer';
$lang['network_visualiser_traffic_summary'] = 'Podsumowanie ruchu sieciowego';
