<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['network_visualiser_app_description'] = 'Aplikacja Wizualizator sieci przechwytuje i wyświetla przepływ danych w Twojej sieci w czasie rzeczywistym. Wyświetla lokalizację źródłową, miejsce docelowe oraz informacje o protokole. Dodatkowo widoczna jest zajętość pasma oraz ilość danych przechwyconych w określonym przedziale czasu.';
$lang['network_visualiser_app_name'] = 'Wizualizator sieci';
$lang['network_visualiser_display'] = 'Wyświetl';
$lang['network_visualiser_display_invalid'] = 'Wyświetlenie jest nieprawidłowe.';
$lang['network_visualiser_interval'] = 'Okres odświeżania (w sekundach)';
$lang['network_visualiser_interval_is_invalid'] = 'Przedział czasu jest nieprawidłowy.';
$lang['network_visualiser_report'] = 'Format raportu';
$lang['network_visualiser_report_detailed'] = 'Tabelaryczny - szczegółowy';
$lang['network_visualiser_report_graphical'] = 'Graficzny';
$lang['network_visualiser_report_invalid'] = 'Typ raportu jest nieprawidłowy.';
$lang['network_visualiser_report_simple'] = 'Tabelaryczny - ogólny';
$lang['network_visualiser_top_users'] = 'Najbardziej obciążający pasmo';
$lang['network_visualiser_total_transfer'] = 'Całkowity transfer';
$lang['network_visualiser_traffic_summary'] = 'Podsumowanie ruchu sieciowego';
